config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/site/admin', as: 'rails_admin'
  	root to: "inicio#index"
  	get 'whatsapp/index'
  	get 'inicio/index'
    get 'preco/index'
  	get 'produto/index'
  	get 'produto/index/:id', to: "produto#index"
  	post 'whatsapp/index'
  	resources :whatsapp_infos
  	devise_for :users
end

app/models/about.rb
class About < ApplicationRecord
  # validates :description, presence: true,:allow_nil => false
	
  before_create :deleta_registro
	def deleta_registro
		About.first.destroy if About.count > 0
	end

	
rails_admin do
      label " Sobre Nós"
      label_plural " Sobre Nós"
      weight 4
      navigation_icon 'icon-pencil'
      edit do
        configure :description do
        label 'Descrição'
        end
      end
      list do
        configure :description do
        label 'Descrição'
        end
        field :description
      end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/information.rb
class Information < ApplicationRecord
	has_one_attached :image #virtual não precisa estar no banco
	validates :title, presence: true,:allow_nil => false
	validates :description, presence: true,:allow_nil => false
	validates :image, presence: true,:allow_nil => false

	rails_admin do
	    label " Serviços"
    	label_plural " Serviços"
      navigation_icon 'icon-wrench'
    	weight 3
    	edit do
      		configure :image do
        		label "Imagem"
      		end
      		configure :title do
        		label 'Titulo'
      		end
      		configure :description do
        		label 'Descrição'
      		end
    	end
    	list do
      		configure :title do
        		label 'Titulo'
      		end
      		configure :description do
        		label 'Descrição'
      		end
      		configure :image do
        		label 'Imagem'
      		end
      		field :title
      		field :description
      		field :image
    	end
	end
end

app/models/produto.rb
class Produto < ApplicationRecord
enum status: [:ativo, :inativo]
enum category: { "Carne Bovina": 0, "Carne Suína": 1, "Peixes": 2, "Aves": 3, "Carne Assada": 4 , "Outros": 5 }
has_one_attached :image #virtual não precisa estar no banco

# validates :nome, presence: true,:allow_nil => false
# validates :valor, presence: true,:allow_nil => false 
# validates :local, presence: true,:allow_nil => false 
# validates :descricao, presence: true,:allow_nil => false 

#default_scope {where(status: :ativo)}
# scope :em_produtos, -> { where(status: :ativo, local: :produtos) }
# scope :em_promocao,-> { where(sttus: :ativo, local: :promocoes) }

 rails_admin do
     	label " Produtos"
     	label_plural " Produtos"
     	weight 2
     	navigation_icon 'icon-list-alt'
#       edit do
#           configure :image do
#             label "Imagem"
#           end
#           configure :title do
#             label 'Titulo'
#           end
#           configure :description do
#             label 'Descrição'
#           end
#           configure :disable do
#           label "Desabilitar"
#         end
#         configure :imagem do
#           label "Imagem do Produto"
#       	end
#       	configure :nome do
#           label 'Nome'
#       	end
#       	configure :descricao do
#           label 'Descrição'
#       	end
#       	configure :valor do
#           label 'Preço'
#         	#partial "price_partial", valor:10
#         end	
#     end
    end  	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	enum tipo: [:cliente, :admin]
    enum status: [:ativo, :inativo]

  rails_admin do
	   label " Usuário"
     label_plural " Usuários"
     navigation_icon 'icon-user'
     weight 1
    list do
      field :nome
      field :email
      field :tipo
    end
  end
end

app/models/whatsapp_info.rb
class WhatsappInfo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController

  def index
  	@produtos = Produto.order('random()').all
  	@informacoes = Information.all
    @sobre = About.last
  end

end

app/controllers/preco_controller.rb
class PrecoController < ApplicationController
  def index
  end
end

app/controllers/produto_controller.rb
class ProdutoController < ApplicationController
  
  def index
  	@prods = Produto.all
  	if params[:id].present?
 			if params[:id].to_i.is_a? Integer
 				@prods = Produto.where(category: params[:id].to_i)
 			end
  	end
  end

end

app/controllers/whatsapp_controller.rb
class WhatsappController < ApplicationController
  def index
  	WhatsappHelper.whatsapp_envia_mensagem(params[:nome],params[:mensagem])
  	redirect_to root_path, :flash =>{:success => "mensagem enviada, logo retornaremos!"}
  end
end

app/controllers/whatsapp_infos_controller.rb
class WhatsappInfosController < ApplicationController
  before_action :set_whatsapp_info, only: [:show, :edit, :update, :destroy]

  def index
    @whatsapp_infos = WhatsappInfo.all
  end

  def show
  end

  def new
    @whatsapp_info = WhatsappInfo.new
  end

  def edit
  end

  def create
    @whatsapp_info = WhatsappInfo.new(whatsapp_info_params)

    respond_to do |format|
      if @whatsapp_info.save
        format.html { redirect_to @whatsapp_info, notice: 'Whatsapp info was successfully created.' }
        format.json { render :show, status: :created, location: @whatsapp_info }
      else
        format.html { render :new }
        format.json { render json: @whatsapp_info.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @whatsapp_info.update(whatsapp_info_params)
        format.html { redirect_to @whatsapp_info, notice: 'Whatsapp info was successfully updated.' }
        format.json { render :show, status: :ok, location: @whatsapp_info }
      else
        format.html { render :edit }
        format.json { render json: @whatsapp_info.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @whatsapp_info.destroy
    respond_to do |format|
      format.html { redirect_to whatsapp_infos_url, notice: 'Whatsapp info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_whatsapp_info
      @whatsapp_info = WhatsappInfo.find(params[:id])
    end

    def whatsapp_info_params
      params.require(:whatsapp_info).permit(:to)
    end
end

app/helpers/application_helper.rb
require 'twilio-ruby'
module ApplicationHelper

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert alert-#{bootstrap_class_for(msg_type)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end

end

app/helpers/galeria_helper.rb
module GaleriaHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/price_helper.rb
module PriceHelper
end

app/helpers/whatsapp_helper.rb
require 'twilio-ruby'
module WhatsappHelper
  def self.whatsapp_envia_mensagem(nome,mensagem)
    # Your Account Sid and Auth Token from twilio.com/console
    account_sid = 'AC7188d3912601d88c051c7d4a1c2f7742'
    auth_token = '19a3d6f76b93fda3a0f16ccb388ac648'
    @client = Twilio::REST::Client.new(account_sid, auth_token)
    message_1 = @client.messages.create(
                             body: 'MENSAGEM DE '+nome.upcase+": "+mensagem.downcase,
                             from: 'whatsapp:+14155238886',
                             to: 'whatsapp:+556681453092'
                           )
    message_2 = @client.messages.create(
                             body: 'MENSAGEM DE '+nome.upcase+": "+mensagem.downcase,
                             from: 'whatsapp:+14155238886',
                             to: 'whatsapp:+5566981282302'
                             )

    message_3 = @client.messages.create(
                             body: 'MENSAGEM DE '+nome.upcase+": "+mensagem.downcase,
                             from: 'whatsapp:+14155238886',
                             to: 'whatsapp:+5566981369818'
                           )
    puts message_1.sid+ " "+message_2.sid
  end
end

app/helpers/whatsapp_infos_helper.rb
module WhatsappInfosHelper
end

app/views/inicio/_about.html.erb
<div class="container">
  <div class="col-xs-12">
    <h2>Sobre-Nós</h2>
    <p><%= @sobre.description if not @sobre.nil? %></p>
    <!-- <p>Em 2019, aos 20 anos de existência, olhamos para nossa trajetória e para nossos negócios com objetivo de nos preparar para o futuro. Nossa história começou em 1999, quando abrimos a casa de carne Badoi no centro de Campinápolis-MT.</p> -->
  </div>
  <div class="col-xs-6">
    <div class="btn-gamp"><a href="produto/index">Produtos</a></div>
  </div>
  <div class="col-xs-6">
    <div class="gamp-btn"><a href="/#contato">Whatsapp</a></div>
  </div>
</div>

app/views/inicio/_navbar.html.erb
<div class="container-fluid">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
    <div class="navbar-brand">
      <a href="/"><h1>Casa de Carnes Badoi</h1></a>
    </div>
  </div>
  <div class="navbar-collapse collapse">
    <div class="menu">
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation"><a href="/" class="active">Inicio</a></li>
        <li role="presentation"><a href="/#sobre">Sobre-Nós</a></li>
        <li role="presentation"><a href="/produto/index">Produtos</a></li>
        <li role="presentation"><a href="/preco/index">Preços</a></li>
        <li role="presentation"><a href="/#especialidades">Serviços</a></li>
        <li role="presentation"><a href="/#contato">Contato</a></li>
        <li role="presentation"><a href="/site/admin">Admin</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/inicio/_produtos.html.erb
<div class="text-center">
  <h2>PRODUTOS</h2>
  <p>Cortes de carnes especiais, suínos, aves e peixes para os amantes da boa gastronomia. Os produtos se destacam pela sua excelência, especialmente os alimentos frescos.</p>
</div>
<div class="container">

<% @produtos.each do |produto| %>
  <div class="col-md-4">
    <figure class="effect-marley-1">
      <%= cl_image_tag(produto.image.key,class:"img-responsive",:transformation=>[{:width=>350,:height=>250,:crop=>"scale"}]) %>
         <figcaption>
       <h4><%= produto.nome.titleize %></h4> 
      <h6><%= produto.descricao %></h6>
      <% if controller_name != "inicio" %>
        <p>Valor Kg R$:
        <% p ' ---' %> 
        <% p produto.valor %> 
        </p>
      <% end %>
    </figcaption>
    </figure>
  </div>
<% end %>
</div>

app/views/inicio/_services.html.erb
<div class="container">
  <div class="text-center">
    <h2>Nossos Serviços</h2>
  </div>
  <% @informacoes.each do |informacao| %>
  <div class="col-md-3 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
    <i><%= cl_image_tag(informacao.image.key,class:"img-responsive", :transformation=>[{:width=>190,:height=>100,:crop=>"scale"}]) %></i> 
    <h3><%= informacao.title.titleize %></h3>
    <p><%= informacao.description %></p>
  </div>
  <% end %>
</div>
   <!--  
    <h3>Carnes Especiais</h3>
    <p>Peixes Variados.</p>
  </div> -->

app/views/inicio/_slider.html.erb
<div id="about-slider">
  <div id="carousel-slider" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators visible-xs">
      <li data-target="#carousel-slider" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-slider" data-slide-to="1"></li>
      <li data-target="#carousel-slider" data-slide-to="2"></li>
    </ol>

    <div class="carousel-inner">
      <div class="item active">
        <img src="/img/principal.jpg" class="img-responsive" alt="">
        <div class="carousel-caption">
          <!-- <div class="wow fadeInUp" data-wow-offset="0" data-wow-delay="0.3s">
            <h2><span>Variedades em Carnes</span></h2>
          </div>
           -->

          <div class="wow fadeInUp" data-wow-offset="0" data-wow-delay="0.3s">
            <h2><span>
          <div class="col-md-10 col-md-offset-1 hidden-xs">
            <div class="wow fadeInUp" data-wow-offset="0" data-wow-delay="0.6s">
              <p>Carne Bovina, Suínos, Peixes e Aves</p>
            </div>
          </div>
          </span></h2>
          </div>
          <!-- <div class="wow fadeInUp" data-wow-offset="0" data-wow-delay="0.9s">
            <form class="form-inline">
              <div class="form-group">
                <button type="livedemo" name="Live Demo" class="btn btn-primary btn-lg" required="required">Live Demo</button>
              </div>
              <div class="form-group">
                <button type="getnow" name="Get Now" class="btn btn-primary btn-lg" required="required">Get Now</button>
              </div>
            </form>
          </div> -->
        </div>
      </div>

      <div class="item">
        <img src="/img/principal.jpg" class="img-responsive" alt="">
        <div class="carousel-caption">
          <div class="wow fadeInUp" data-wow-offset="0" data-wow-delay="1.0s">
            <h2><span><div class="col-md-10 col-md-offset-1">
            <div class="wow fadeInUp" data-wow-offset="0" data-wow-delay="0.6s">
              <p>Trabalhando Com Você Desde 1999</p>
            </div>
          </div>
          </span></h2>
          </div>
          <!-- <div class="wow fadeInUp" data-wow-offset="0" data-wow-delay="1.6s">
            <form class="form-inline">
              <div class="form-group">
                <button type="livedemo" name="purchase" class="btn btn-primary btn-lg" required="required">Live Demo</button>
              </div>
              <div class="form-group">
                <button type="getnow" name="subscribe" class="btn btn-primary btn-lg" required="required">Get Now</button>
              </div>
            </form>
          </div> -->
        </div>
      </div>
      <div class="item">
        <img src="/img/principal.jpg" class="img-responsive" alt="">
        <div class="carousel-caption">
          <div class="wow fadeInUp" data-wow-offset="0" data-wow-delay="0.3s">
             <h2><span><div class="col-md-10 col-md-offset-1">
            <div class="wow fadeInUp" data-wow-offset="0" data-wow-delay="0.6s">
              <p>Atender Bem Para Atender Sempre</p>
            </div>
          </div>
          </span></h2>
          </div>
          <!-- <div class="wow fadeInUp" data-wow-offset="0" data-wow-delay="0.9s">
            <form class="form-inline">
              <div class="form-group">
                <button type="livedemo" name="purchase" class="btn btn-primary btn-lg" required="required">Galeria</button>
              </div>
              <div class="form-group">
                <button type="getnow" name="subscribe" class="btn btn-primary btn-lg" required="required">Get Now</button>
              </div>
            </form>
          </div> -->
        </div>
      </div>
    </div>

    <a class="left carousel-control hidden-xs" href="#carousel-slider" data-slide="prev">
                <i class="fa fa-angle-left"></i>
            </a>

    <a class=" right carousel-control hidden-xs" href="#carousel-slider" data-slide="next">
                <i class="fa fa-angle-right"></i>
            </a>
  </div>
  <!--/#carousel-slider-->
</div>
<!--/#about-slider-->

app/views/inicio/index.html.erb
<div class="slider">
  <%= render partial: "inicio/slider" %>
</div>
<!--/#slider-->
<div id= "sobre">
  <div class="about">
    <%= render partial: "inicio/about" %>
  </div>
</div>
<section class="action">
  <div class="container">
    <div class="left-text hidden-xs">
      <h4><font color="#fff" size="6">Espaço Interno</font></h4>
      <p><em><font color="#fff" size="4">Refrigeração moderna e adequada.</font></em><br><br><font color="#fff" size="4">Com a melhor estrutura de toda a cidade.</font>
        <font color="#fff" size="4">A Casa de Carne Badoi desenvolve um trabalho único, oferece produtos de qualidade e preços competitivos.</font>
      </p>
    </div>
    <div class="right-image hidden-xs">
      <div id="slider_int">
        <div id="slider_foto">
          <div id="comslider_in_point_1794033"></div>
          <script type="text/javascript">
            var oCOMScript1794033=document.createElement('script');
            oCOMScript1794033.src="comslider1794033/comsliderd.js?timestamp=1552841375";
            oCOMScript1794033.type='text/javascript';
            document.getElementsByTagName("head").item(0).appendChild(oCOMScript1794033);
          </script>
        </div>
      </div>
    </div>
  </div>
</section>
<div class="gallery">
  <%= render partial: "inicio/produtos" %>
</div>
<div id="especialidades">
  <div class="services">
    <%= render partial: "inicio/services" %>
  </div>
</div>

app/views/layouts/_fav.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/img/fav/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/img/fav/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/img/fav/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/img/fav/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/img/fav/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/img/fav/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/img/fav/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/img/fav/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/img/fav/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/img/fav/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/img/fav/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/img/fav/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/img/fav/favicon-16x16.png">
<link rel="manifest" href="/img/fav/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/img/fav/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

app/views/layouts/_whatsapp.html.erb
<div class="col-xs-12">
<%= flash_messages if defined? (flash[:success]["mensagem"].size) %>
</div>
<form action="/whatsapp/index" method="post">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <h4 style="color:#fff">Envie uma mensagem para nosso Whatsapp!</h4>
    <input type="text" name="nome" class="form-control" placeholder="Nome completo" required="">
    <input type="text" name="celular" class="form-control" placeholder="Número do Celular" required="">
    <input type="text" name="mensagem" class="form-control" placeholder="Mensagem" required="">
    <!-- <input type="email" name="email" class="form-control" placeholder="Endereço de e-mail" required=""> -->
    <!-- <input type="password" name="password" class="form-control" placeholder="senha" required=""> -->
    <button class="submit-btn form-control" id="form-submit">Enviar</button>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Casa de carne Badoi</title>
  <%= render partial: "layouts/fav" %>
  <!-- Bootstrap -->
  <!-- <link href="/css/bootstrap.min.css" rel="stylesheet"> -->
  <link href="/css/bootstrap.css" rel="stylesheet">
  <link rel="stylesheet" href="/css/font-awesome.min.css">
  <link rel="stylesheet" href="/css/animate.css">
  <link href="/css/animate.min.css" rel="stylesheet">
  <link href="/css/style.css" rel="stylesheet" />
</head>
<body>
  <header id="header">
    <nav class="navbar navbar-default navbar-static-top" role="banner">
      <%= render partial: "inicio/navbar"%>
    </nav>
  </header>
    <%= yield %>
  <footer>
  <div id= "contato">
    <div class="container">
      <div class="col-xs-12 col-md-4 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
        <h4>Nosso Endereço</h4>
        <p></p>
        <div class="contact-info">
          <ul>
            <li><i class="fa fa-home fa"></i><b> Rua Vicente José de Oliveira, Nº: 930, Centro, Campinápolis-MT </b></li>
            <li><i class="fa fa-phone fa"></i><b> (66) 98128-2302</b></li>
            <li><i class="fa fa-envelope fa"></i><b> badoi@campinapolis.com</b></li>
          </ul>
        </div>
      </div>

      <div class="col-xs-12 col-md-4 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
        <div class="text-center">
            <h4><b>Veja Nossa Localização</b></h4>
            <figure class="indent-bot">
              <iframe width="100%" height="300px" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d241.37889022079912!2d-52.796825452402!3d-14.538432308099283!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x36489ec670f62c8c!2sCasa+de+Carne+Badoi!5e0!3m2!1spt-BR!2sbr!4v1551982430187" width="100%" height="100%" frameborder="0" style="border:0" allowfullscreen>
              </iframe>
            </figure>
        </div>
       <!--  </div> -->
      </div>

      <!-- <div class="col-md-4 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="900ms"> -->
      <div class="col-xs-12 col-md-4 wow fadeInDown">
          <div class="entry-form">
            <%= render "layouts/whatsapp" %>
          </div>
      </div>
    </div>
  </footer>

</div>
</div>

  <div class="sub-footer">
    <div class="container-fluid">
      <div class="social-icon">
        <div class="col-xs-6 col-md-4">
          <div class="credits">
            <b>LINKS UTEIS</b>
          </div>
          <ul class="social-network">
            <li><a href="https://www.facebook.com/campinapolispontocom/" class="fb tool-tip" title="Facebook"><i class="fa fa-facebook"></i></a></li>
            <!-- <li><a href="#" class="twitter tool-tip" title="Twitter"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#" class="gplus tool-tip" title="Google Plus"><i class="fa fa-google-plus"></i></a></li>-->
            <!-- <li><a href="#" class="linkedin tool-tip" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>-->
            <li><a href="https://www.youtube.com/watch?v=YEy5qNO2qzw" class="ytube tool-tip" title="Churrasco de Picanha"><i class="fa fa-youtube-play"></i></a></li>
            <li><a href="https://www.youtube.com/watch?v=An3bxm8mzCg" class="ytube tool-tip" title="Churrasco de Contra filé"><i class="fa fa-youtube-play"></i></a></li>
            <li><a href="https://www.youtube.com/watch?v=lsqLeI_EQYE" class="ytube tool-tip" title="Churrasco de Frango"><i class="fa fa-youtube-play"></i></a></li>
            <li><a href="https://www.youtube.com/watch?v=Q5VAd2lbN_c" class="ytube tool-tip" title="Churrasco de Linguiça"><i class="fa fa-youtube-play"></i></a></li>
          </ul>
        </div>
      </div>
      <div class="col-xs-12 col-md-4 col-md-offset-4">
        <div class="copyright">
          <b>&copy; campinapolis.com 2019</b>
          <div class="credits">
            <!--
              All the links in the footer should remain intact.
              You can delete the links only if you purchased the pro version.
              Licensing information: https://bootstrapmade.com/license/
              Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Day
            -->
            <a href="https://campinapolis.com/"><b>ir para o site</b></a>
          </div>
        </div>
      </div>
    </div>
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="/js/jquery.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="/js/bootstrap.min.js"></script>
  <script src="/js/wow.min.js"></script>
  <script>
    //wow = new WOW({}).init();
  </script>
</body>

</html>

app/views/whatsapp/index.html.erb
<h1>Whatsapp#index</h1>
<div class="text-center">
<h1><p>Mensagem enviada com Sucesso, logo retornaremos!</p></h1>

app/views/whatsapp_infos/_form.html.erb
<%= form_with(model: whatsapp_info, local: true) do |form| %>
  <% if whatsapp_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(whatsapp_info.errors.count, "error") %> prohibited this whatsapp_info from being saved:</h2>

      <ul>
      <% whatsapp_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :to %>
    <%= form.text_field :to %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/whatsapp_infos/edit.html.erb
<h1>Editing Whatsapp Info</h1>

<%= render 'form', whatsapp_info: @whatsapp_info %>

<%= link_to 'Show', @whatsapp_info %> |
<%= link_to 'Back', whatsapp_infos_path %>

app/views/whatsapp_infos/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Whatsapp Infos</h1>
<table>
  <thead>
    <tr>
      <th>To</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @whatsapp_infos.each do |whatsapp_info| %>
      <tr>
        <td><%= whatsapp_info.to %></td>
        <td><%= link_to 'Show', whatsapp_info %></td>
        <td><%= link_to 'Edit', edit_whatsapp_info_path(whatsapp_info) %></td>
        <td><%= link_to 'Destroy', whatsapp_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Whatsapp Info', new_whatsapp_info_path %>

app/views/whatsapp_infos/new.html.erb
<h1>New Whatsapp Info</h1>

<%= render 'form', whatsapp_info: @whatsapp_info %>

<%= link_to 'Back', whatsapp_infos_path %>

app/views/whatsapp_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>To:</strong>
  <%= @whatsapp_info.to %>
</p>

<%= link_to 'Edit', edit_whatsapp_info_path(@whatsapp_info) %> |
<%= link_to 'Back', whatsapp_infos_path %>